//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egs.EgsDeviceControlCore.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egs.EgsDeviceControlCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   by Device (for Lower Spec PC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_ByDevice_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_ByDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   by Host Application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_ByHostApplication_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_ByHostApplication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Borders and Pointers of Camera View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   320*240 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   384*240 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   640*480 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Borders and Pointers Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewUserControlModel_ImageSetIndex_Description {
            get {
                return ResourceManager.GetString("CameraViewUserControlModel_ImageSetIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Borders and Pointers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewUserControlModel_IsToDrawImageSet_Description {
            get {
                return ResourceManager.GetString("CameraViewUserControlModel_IsToDrawImageSet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Dragging に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_CanDragMove_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMove_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disable Dragging Camera View Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_CanDragMoveDisabled_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMoveDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Dragging Camera View Window に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_CanDragMoveEnabled_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMoveEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Resizing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_CanResize_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanResize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Menu by Tap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_CanShowMenu_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanShowMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window Position and Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_LocationAndSize_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_LocationAndSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bring Camera View to Front に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_Topmost_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_Topmost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When to Show / Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowModel_WindowStateControlMethodSetByUser_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_WindowStateControlMethodSetByUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep Minimized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_KeepMinimized_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_KeepMinimized_Descriptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_KeepNormal_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_KeepNormal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera View Window State Control By Applications に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use User Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_UseUsersControlMethods_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_UseUsersControlMethods_D" +
                        "escription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show/Hide Manually by Selecting ZKOO Icon on Task Bar or System Tray.  Hide by Selecting &quot;Minimize&quot; Button on the Menu. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ManualOnOff_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ManualOnOff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show When Face Recognition Starts, and Hide After Recognized.  Show During Hand Tracking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandDetectionStarts_ShowWhenHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandDetectionStarts_ShowWhenHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show When Face Recognition Starts, and Hide After Recognized.  Show for a While After Hand Tracking Starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandDetectionStarts_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandDetectionStarts_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingSt" +
                        "arts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show When Face Recognition Starts.  Hide Soon After Hand Tracking Starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show When a Face is Recognized.  Hide Soon After Hand Tracking Starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhenHandDetectionEnds_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhe" +
                        "nHandDetectionEnds_HideSoonAfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show When a Face is Recognized. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhenHandDetectionEnds_HideWhenHandTrackingEnds_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhe" +
                        "nHandDetectionEnds_HideWhenHandTrackingEnds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show for a While After Hand Tracking Starts. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideSoon" +
                        "AfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show During Hand Tracking. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideWhenHandTrackingEnds_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideWhen" +
                        "HandTrackingEnds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera View Auto On/Off Control に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1x1 (not tested yet) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureBinningDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2x2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureBinningDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3x3 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureBinningDetail_Value3_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4x4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureBinningDetail_Value4_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureExposureModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureExposureModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Detected Faces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureExposureModeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureFpsDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   100 fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureFpsDetail_Value100_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   120 fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CaptureFpsDetail_Value120_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value120_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accept に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Accept {
            get {
                return ResourceManager.GetString("CommonStrings_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} failed to start. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Application0FailedToStart {
            get {
                return ResourceManager.GetString("CommonStrings_Application0FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Application0IsAlreadyRunning {
            get {
                return ResourceManager.GetString("CommonStrings_Application0IsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No update is available.  You have installed the latest {0} application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Application0IsLatest {
            get {
                return ResourceManager.GetString("CommonStrings_Application0IsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Application0Started {
            get {
                return ResourceManager.GetString("CommonStrings_Application0Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ApplicationVersion {
            get {
                return ResourceManager.GetString("CommonStrings_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Application will exit. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ApplicationWillExit {
            get {
                return ResourceManager.GetString("CommonStrings_ApplicationWillExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Auto {
            get {
                return ResourceManager.GetString("CommonStrings_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Bottom {
            get {
                return ResourceManager.GetString("CommonStrings_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_CameraView {
            get {
                return ResourceManager.GetString("CommonStrings_CameraView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Cancel {
            get {
                return ResourceManager.GetString("CommonStrings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New {0} application is available.  Please select OK to access {0} website to download new application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_CanDownloadNewApplication0 {
            get {
                return ResourceManager.GetString("CommonStrings_CanDownloadNewApplication0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check for Updates に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_CheckForApplicationUpdates {
            get {
                return ResourceManager.GetString("CommonStrings_CheckForApplicationUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Commands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Commands {
            get {
                return ResourceManager.GetString("CommonStrings_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Confirmation {
            get {
                return ResourceManager.GetString("CommonStrings_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Downloading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Downloading {
            get {
                return ResourceManager.GetString("CommonStrings_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Drag {
            get {
                return ResourceManager.GetString("CommonStrings_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Exit {
            get {
                return ResourceManager.GetString("CommonStrings_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flick に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Flick {
            get {
                return ResourceManager.GetString("CommonStrings_Flick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Gesture {
            get {
                return ResourceManager.GetString("CommonStrings_Gesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture Cursor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_GestureCursor {
            get {
                return ResourceManager.GetString("CommonStrings_GestureCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Height に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Height {
            get {
                return ResourceManager.GetString("CommonStrings_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_IsConnected {
            get {
                return ResourceManager.GetString("CommonStrings_IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Connected に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_IsNotConnected {
            get {
                return ResourceManager.GetString("CommonStrings_IsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Left {
            get {
                return ResourceManager.GetString("CommonStrings_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Log {
            get {
                return ResourceManager.GetString("CommonStrings_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Manual {
            get {
                return ResourceManager.GetString("CommonStrings_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Maximum {
            get {
                return ResourceManager.GetString("CommonStrings_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Minimize {
            get {
                return ResourceManager.GetString("CommonStrings_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Minimum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Minimum {
            get {
                return ResourceManager.GetString("CommonStrings_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_More {
            get {
                return ResourceManager.GetString("CommonStrings_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Move {
            get {
                return ResourceManager.GetString("CommonStrings_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Options {
            get {
                return ResourceManager.GetString("CommonStrings_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check your network connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_PleaseCheckYourNetworkConnection {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseCheckYourNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect the ZKOO camera. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_PleaseConnectTheZkooCamera {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseConnectTheZkooCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect your host device to internet, and then click OK. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_PleaseConnectYourHostDeviceToInternetAndThenClickOk {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseConnectYourHostDeviceToInternetAndThenClickOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect ZKOO with PC 
        ///before starting ZKOO application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_PleaseStartHostApplicationsAfterZkooIsConnected {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseStartHostApplicationsAfterZkooIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preferences に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Preferences {
            get {
                return ResourceManager.GetString("CommonStrings_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Progress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Progress {
            get {
                return ResourceManager.GetString("CommonStrings_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ResetDevice {
            get {
                return ResourceManager.GetString("CommonStrings_ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Device? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ResetDeviceConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_ResetDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ResetSettings {
            get {
                return ResourceManager.GetString("CommonStrings_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset Settings to Default? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ResetSettingsConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_ResetSettingsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Right {
            get {
                return ResourceManager.GetString("CommonStrings_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings to Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_SaveSettingsToFlash {
            get {
                return ResourceManager.GetString("CommonStrings_SaveSettingsToFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings to Device? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_SaveSettingsToFlashConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_SaveSettingsToFlashConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Settings {
            get {
                return ResourceManager.GetString("CommonStrings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Skip {
            get {
                return ResourceManager.GetString("CommonStrings_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Start {
            get {
                return ResourceManager.GetString("CommonStrings_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Tap {
            get {
                return ResourceManager.GetString("CommonStrings_Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Top {
            get {
                return ResourceManager.GetString("CommonStrings_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Value {
            get {
                return ResourceManager.GetString("CommonStrings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_Width {
            get {
                return ResourceManager.GetString("CommonStrings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Would you exit {0}? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_WouldYouExitApplication0 {
            get {
                return ResourceManager.GetString("CommonStrings_WouldYouExitApplication0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO recognize your hands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonStrings_ZkooRecognizeYourHands {
            get {
                return ResourceManager.GetString("CommonStrings_ZkooRecognizeYourHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   简体中文 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Chinese_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Chinese_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_English_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_English_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Japanese_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Japanese_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Type_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use OS Culture に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_UseOSCulture_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_UseOSCulture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maximum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByHidReportUpdatedEvent_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByHidReportUpdatedEvent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   30 fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByTimer30Fps_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByTimer30Fps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   60 fps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByTimer60Fps_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByTimer60Fps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture Cursor Drawing Frequency (Smaller Value for Lower Spec PC) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beginner: For slower hand moving and easier tapping.  2 cursors cannot cross. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Standard: For standard speed hand moving.  2 cursors can cross. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fruit Ninja: Good for Fruit Ninja Game.  Cut fruits by fast moving opened hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0: Landscape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value0_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   90: Portrait (flipped) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value1_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   180: Landscape (flipped) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value2_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   270: Portrait に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value3_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceUsageDetail_Value0_Description {
            get {
                return ResourceManager.GetString("DeviceUsageDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DeviceUsageDetail_Value1_Description {
            get {
                return ResourceManager.GetString("DeviceUsageDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Device DevicePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_CameraDeviceDevicePath_Description {
            get {
                return ResourceManager.GetString("EgsDevice_CameraDeviceDevicePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Serial Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_DeviceSerialNumber_Description {
            get {
                return ResourceManager.GetString("EgsDevice_DeviceSerialNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Status に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_DeviceStatusDetailString_Description {
            get {
                return ResourceManager.GetString("EgsDevice_DeviceStatusDetailString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_FirmwareVersion_Description {
            get {
                return ResourceManager.GetString("EgsDevice_FirmwareVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hardware Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_HardwareType_Description {
            get {
                return ResourceManager.GetString("EgsDevice_HardwareType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch Device DevicePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_HidDeviceDevicePath_Description {
            get {
                return ResourceManager.GetString("EgsDevice_HidDeviceDevicePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature [C] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_TemperatureInCelsius_Description {
            get {
                return ResourceManager.GetString("EgsDevice_TemperatureInCelsius_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temperature [F] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDevice_TemperatureInFahrenheit_Description {
            get {
                return ResourceManager.GetString("EgsDevice_TemperatureInFahrenheit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The application will retry sending image file again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_AppWillRetrySendingImageAgain {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_AppWillRetrySendingImageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device Firmware Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DeviceFirmwareUpdate {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DeviceFirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device firmware update was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuCanceled {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device firmware update was completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuCompleted {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Device firmware update was failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuFailed {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image file is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuImageFileIsInvalid {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuImageFileIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please do not disconnect ZKOO from AC adapter and PC. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DoNotDisconnectTheDevice {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DoNotDisconnectTheDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please update device firmware to use ZKOO and ZKOO application by selecting OK.  During update, you need to reboot ZKOO a few times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_PleaseUpdateDeviceFirmware {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_PleaseUpdateDeviceFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart the firmware update process from the beginning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_RestartDfuFromBeginning {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_RestartDfuFromBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update Device Firmware に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_UpdateDeviceFirmware {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_UpdateDeviceFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO needs reboot. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsReboot {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please connect ZKOO with AC adapter and PC and check LED is on. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsToConnectPowerCable {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsToConnectPowerCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please disconnect ZKOO from AC adapter and PC and check LED is off. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsToDisconnectPowerCable {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsToDisconnectPowerCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Source Image Resolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CameraViewImageSourceBitmapSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CameraViewImageSourceBitmapSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera View Image Source Rect in Captured Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CameraViewImageSourceRectInCapturedImage_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CameraViewImageSourceRectInCapturedImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Binning Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CaptureBinning_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureBinning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CaptureExposureMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureExposureMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera Frame Per Second に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CaptureFps_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureFps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture Image Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CaptureImageSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureImageSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CaptureManualExposureParameters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureManualExposureParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture Usage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_CursorSpeedAndPrecisionMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CursorSpeedAndPrecisionMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Primary Screen Orientation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_DeviceRotationAngleInClockwise_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_DeviceRotationAngleInClockwise_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use ZKOO for に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_DeviceUsage_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_DeviceUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Face Detection Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_FaceDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Face Detection Scale (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_FaceDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How to Select a Player に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_FaceSelectionMethodKind_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceSelectionMethodKind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture by Fast Moving Hands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_FastMovingHandsGestureMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FastMovingHandsGestureMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hand Detection Parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_HandDetectionParameters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_HandDetectionParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Host Machine OS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_HostMachineOperatingSystem_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_HostMachineOperatingSystem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect Faces に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectFaces_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectFaces_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detect Hands に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectHands_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectHands_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Draw Borders on Camera View Image By Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToDrawBordersOnCameraViewImageByDevice_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDrawBordersOnCameraViewImageByDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Face Detection Region に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToFixFaceDetectionRegion_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixFaceDetectionRegion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Hand Detection Regions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToFixHandDetectionRegions_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixHandDetectionRegions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Hand Tracking Areas に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToFixHandTrackingAreas_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixHandTrackingAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fix Screen Mapped Areas に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToFixScreenMappedAreas_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixScreenMappedAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Touch Information to Apps に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToSendEgsGestureHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendEgsGestureHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Hovering State on Touch Information to OS (On Windows 10, problems can happen) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToSendHoveringStateOnTouchScreenHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendHoveringStateOnTouchScreenHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send Touch Information to OS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_IsToSendTouchScreenHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendTouchScreenHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Close Hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandCloseHand_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandCloseHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Detection Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Detection Scale (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Inner Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandInnerRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandInnerRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Outer Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandOuterRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandOuterRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Screen Mapped Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandScreenMappedAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandScreenMappedAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand Tracking Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LeftHandTrackingAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandTrackingAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focal Length [mm] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LensEquivalentFocalLengthInMillimeters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LensEquivalentFocalLengthInMillimeters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F Number に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_LensFNumber_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LensFNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Model Set ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_ModelSetId_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_ModelSetId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_PowerMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_PowerMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Close Hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandCloseHand_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandCloseHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Detection Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Detection Scale (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Inner Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandInnerRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandInnerRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Outer Rotation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandOuterRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandOuterRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Screen Mapped Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandScreenMappedAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandScreenMappedAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand Tracking Area (when fixed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_RightHandTrackingAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandTrackingAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Screen Mapped Area Resolution Size on Device に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_ScreenMappedAreaResolutionSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_ScreenMappedAreaResolutionSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exposure [ms] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_SensorExposureTimeInMilliseconds_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_SensorExposureTimeInMilliseconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One Pixel Side Length [mm] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_SensorOnePixelSideLengthInMillimeters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_SensorOnePixelSideLengthInMillimeters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Brightness of Status LED に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_StatusLedBrightnessMaximum_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_StatusLedBrightnessMaximum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch Interface Kind に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_TouchInterfaceKind_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TouchInterfaceKind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch Target Screen Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_TouchTargetScreenSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TouchTargetScreenSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Number of Trackable Objects に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_TrackableHandsCount_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TrackableHandsCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB Communication Protocol Revision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EgsDeviceSettings_UsbProtocolRevision_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_UsbProtocolRevision_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto: Select a person who moves a hand automatically に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value0_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One by One: Select a person one by one to find who moves a hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value1_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Most Center: Select the most center person in Camera View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value2_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FastMovingHandsGestureModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("FastMovingHandsGestureModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FastMovingHandsGestureModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("FastMovingHandsGestureModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareTypeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO for Kickstarter Backers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareTypeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MA2150 + IMX208 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareTypeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MA2150 + IMX208 + PIC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HardwareTypeDetail_Value3_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Windows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HostMachineOperatingSystemDetail_Value0_Description {
            get {
                return ResourceManager.GetString("HostMachineOperatingSystemDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Android に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HostMachineOperatingSystemDetail_Value1_Description {
            get {
                return ResourceManager.GetString("HostMachineOperatingSystemDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Five Fingers for TV に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelSetIdDetail_Value0_Description {
            get {
                return ResourceManager.GetString("ModelSetIdDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wands? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ModelSetIdDetail_Value1_Description {
            get {
                return ResourceManager.GetString("ModelSetIdDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Found Hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_FirstFoundHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_FirstFoundHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left Hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_LeftHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_LeftHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_None_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_None_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right Hand に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_RightHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_RightHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move Mouse Cursor&apos;s Position to Follow Gesture Cursor&apos;s Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gesture Cursor Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnePersonBothHandsViewModel_GestureCursorType_Description {
            get {
                return ResourceManager.GetString("OnePersonBothHandsViewModel_GestureCursorType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Gesture Cursors に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OnePersonBothHandsViewModel_IsToShowGestureCursors_Description {
            get {
                return ResourceManager.GetString("OnePersonBothHandsViewModel_IsToShowGestureCursors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Active に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("PowerModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   StandingBy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PowerModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("PowerModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Advanced に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_AdvancedSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_AdvancedSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Analog Gain (1-32):  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_AnalogGain_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_AnalogGain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_BasicSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_BasicSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_CameraViewSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_CameraViewSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_DeveloperSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_DeveloperSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exvision に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_ExvisionSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_ExvisionSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options for Lower Spec PC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_OptionsForLowerSpecPc_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_OptionsForLowerSpecPc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_StartTutorial_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_StartTutorial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial App に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsUserControl_TutorialAppSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_TutorialAppSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MultiTouch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TouchInterfaceKindDetail_Value0_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SingleTouch (for Android) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TouchInterfaceKindDetail_Value1_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TouchInterfaceKindDetail_Value2_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value2_Description", resourceCulture);
            }
        }
    }
}
