//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egs.EgsDeviceControlCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egs.EgsDeviceControlCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Device (for Lower Spec PC).
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_ByDevice_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_ByDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Host Application.
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_ByHostApplication_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_ByHostApplication_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Borders and Pointers of Camera View.
        /// </summary>
        public static string CameraViewBordersAndPointersAreDrawnByDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewBordersAndPointersAreDrawnByDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 320*240.
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 384*240.
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 640*480.
        /// </summary>
        public static string CameraViewImageSourceBitmapSizeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CameraViewImageSourceBitmapSizeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borders and Pointers Type.
        /// </summary>
        public static string CameraViewUserControlModel_ImageSetIndex_Description {
            get {
                return ResourceManager.GetString("CameraViewUserControlModel_ImageSetIndex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Borders and Pointers.
        /// </summary>
        public static string CameraViewUserControlModel_IsToDrawImageSet_Description {
            get {
                return ResourceManager.GetString("CameraViewUserControlModel_IsToDrawImageSet_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dragging.
        /// </summary>
        public static string CameraViewWindowModel_CanDragMove_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMove_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Dragging Camera View Window.
        /// </summary>
        public static string CameraViewWindowModel_CanDragMoveDisabled_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMoveDisabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Dragging Camera View Window.
        /// </summary>
        public static string CameraViewWindowModel_CanDragMoveEnabled_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanDragMoveEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Resizing.
        /// </summary>
        public static string CameraViewWindowModel_CanResize_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanResize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Menu by Tap.
        /// </summary>
        public static string CameraViewWindowModel_CanShowMenu_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_CanShowMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Position and Size.
        /// </summary>
        public static string CameraViewWindowModel_LocationAndSize_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_LocationAndSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Camera View to Front.
        /// </summary>
        public static string CameraViewWindowModel_Topmost_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_Topmost_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When to Show / Hide.
        /// </summary>
        public static string CameraViewWindowModel_WindowStateControlMethodSetByUser_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowModel_WindowStateControlMethodSetByUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Minimized.
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_KeepMinimized_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_KeepMinimized_Descriptio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Normal.
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_KeepNormal_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_KeepNormal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Window State Control By Applications.
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use User Settings.
        /// </summary>
        public static string CameraViewWindowStateHostApplicationsControlMethodDetail_UseUsersControlMethods_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateHostApplicationsControlMethodDetail_UseUsersControlMethods_D" +
                        "escription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Manually by Selecting ZKOO Icon on Task Bar or System Tray.  Hide by Selecting &quot;Minimize&quot; Button on the Menu..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ManualOnOff_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ManualOnOff_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show When Face Recognition Starts, and Hide After Recognized.  Show During Hand Tracking..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandDetectionStarts_ShowWhenHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandDetectionStarts_ShowWhenHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show When Face Recognition Starts, and Hide After Recognized.  Show for a While After Hand Tracking Starts..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandDetectionStarts_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandDetectionStarts_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingSt" +
                        "arts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show When Face Recognition Starts.  Hide Soon After Hand Tracking Starts..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenFaceDetectionStarts_HideSoo" +
                        "nAfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show When a Face is Recognized.  Hide Soon After Hand Tracking Starts..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhenHandDetectionEnds_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhe" +
                        "nHandDetectionEnds_HideSoonAfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show When a Face is Recognized..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhenHandDetectionEnds_HideWhenHandTrackingEnds_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandDetectionStarts_HideWhe" +
                        "nHandDetectionEnds_HideWhenHandTrackingEnds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for a While After Hand Tracking Starts..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideSoonAfterHandTrackingStarts_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideSoon" +
                        "AfterHandTrackingStarts_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show During Hand Tracking..
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideWhenHandTrackingEnds_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_ShowWhenHandTrackingStarts_HideWhen" +
                        "HandTrackingEnds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Auto On/Off Control.
        /// </summary>
        public static string CameraViewWindowStateUsersControlMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CameraViewWindowStateUsersControlMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1x1 (not tested yet).
        /// </summary>
        public static string CaptureBinningDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x2.
        /// </summary>
        public static string CaptureBinningDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x3.
        /// </summary>
        public static string CaptureBinningDetail_Value3_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x4.
        /// </summary>
        public static string CaptureBinningDetail_Value4_Description {
            get {
                return ResourceManager.GetString("CaptureBinningDetail_Value4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string CaptureExposureModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string CaptureExposureModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Detected Faces.
        /// </summary>
        public static string CaptureExposureModeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CaptureExposureModeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string CaptureFpsDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 fps.
        /// </summary>
        public static string CaptureFpsDetail_Value100_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value100_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120 fps.
        /// </summary>
        public static string CaptureFpsDetail_Value120_Description {
            get {
                return ResourceManager.GetString("CaptureFpsDetail_Value120_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string CommonStrings_Accept {
            get {
                return ResourceManager.GetString("CommonStrings_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed to start..
        /// </summary>
        public static string CommonStrings_Application0FailedToStart {
            get {
                return ResourceManager.GetString("CommonStrings_Application0FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running..
        /// </summary>
        public static string CommonStrings_Application0IsAlreadyRunning {
            get {
                return ResourceManager.GetString("CommonStrings_Application0IsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update is available.  You have installed the latest {0} application..
        /// </summary>
        public static string CommonStrings_Application0IsLatest {
            get {
                return ResourceManager.GetString("CommonStrings_Application0IsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started..
        /// </summary>
        public static string CommonStrings_Application0Started {
            get {
                return ResourceManager.GetString("CommonStrings_Application0Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string CommonStrings_ApplicationVersion {
            get {
                return ResourceManager.GetString("CommonStrings_ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application will exit..
        /// </summary>
        public static string CommonStrings_ApplicationWillExit {
            get {
                return ResourceManager.GetString("CommonStrings_ApplicationWillExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string CommonStrings_Auto {
            get {
                return ResourceManager.GetString("CommonStrings_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string CommonStrings_Bottom {
            get {
                return ResourceManager.GetString("CommonStrings_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View.
        /// </summary>
        public static string CommonStrings_CameraView {
            get {
                return ResourceManager.GetString("CommonStrings_CameraView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CommonStrings_Cancel {
            get {
                return ResourceManager.GetString("CommonStrings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0} application is available.  Please select OK to access {0} website to download new application..
        /// </summary>
        public static string CommonStrings_CanDownloadNewApplication0 {
            get {
                return ResourceManager.GetString("CommonStrings_CanDownloadNewApplication0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CommonStrings_CheckForApplicationUpdates {
            get {
                return ResourceManager.GetString("CommonStrings_CheckForApplicationUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string CommonStrings_Commands {
            get {
                return ResourceManager.GetString("CommonStrings_Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string CommonStrings_Confirmation {
            get {
                return ResourceManager.GetString("CommonStrings_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Detection.
        /// </summary>
        public static string CommonStrings_DecreaseFalseNegativeRate {
            get {
                return ResourceManager.GetString("CommonStrings_DecreaseFalseNegativeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Detection.
        /// </summary>
        public static string CommonStrings_DecreaseFalsePositiveRate {
            get {
                return ResourceManager.GetString("CommonStrings_DecreaseFalsePositiveRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string CommonStrings_Downloading {
            get {
                return ResourceManager.GetString("CommonStrings_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        public static string CommonStrings_Drag {
            get {
                return ResourceManager.GetString("CommonStrings_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string CommonStrings_Exit {
            get {
                return ResourceManager.GetString("CommonStrings_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flick.
        /// </summary>
        public static string CommonStrings_Flick {
            get {
                return ResourceManager.GetString("CommonStrings_Flick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture.
        /// </summary>
        public static string CommonStrings_Gesture {
            get {
                return ResourceManager.GetString("CommonStrings_Gesture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Cursor.
        /// </summary>
        public static string CommonStrings_GestureCursor {
            get {
                return ResourceManager.GetString("CommonStrings_GestureCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string CommonStrings_Height {
            get {
                return ResourceManager.GetString("CommonStrings_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string CommonStrings_IsConnected {
            get {
                return ResourceManager.GetString("CommonStrings_IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        public static string CommonStrings_IsNotConnected {
            get {
                return ResourceManager.GetString("CommonStrings_IsNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string CommonStrings_Left {
            get {
                return ResourceManager.GetString("CommonStrings_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string CommonStrings_Log {
            get {
                return ResourceManager.GetString("CommonStrings_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string CommonStrings_Manual {
            get {
                return ResourceManager.GetString("CommonStrings_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string CommonStrings_Maximum {
            get {
                return ResourceManager.GetString("CommonStrings_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string CommonStrings_Minimize {
            get {
                return ResourceManager.GetString("CommonStrings_Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string CommonStrings_Minimum {
            get {
                return ResourceManager.GetString("CommonStrings_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string CommonStrings_More {
            get {
                return ResourceManager.GetString("CommonStrings_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string CommonStrings_Move {
            get {
                return ResourceManager.GetString("CommonStrings_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string CommonStrings_Options {
            get {
                return ResourceManager.GetString("CommonStrings_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your network connection..
        /// </summary>
        public static string CommonStrings_PleaseCheckYourNetworkConnection {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseCheckYourNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect the ZKOO camera..
        /// </summary>
        public static string CommonStrings_PleaseConnectTheZkooCamera {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseConnectTheZkooCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your host device to internet, and then click OK..
        /// </summary>
        public static string CommonStrings_PleaseConnectYourHostDeviceToInternetAndThenClickOk {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseConnectYourHostDeviceToInternetAndThenClickOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect ZKOO with PC 
        ///before starting ZKOO application..
        /// </summary>
        public static string CommonStrings_PleaseStartHostApplicationsAfterZkooIsConnected {
            get {
                return ResourceManager.GetString("CommonStrings_PleaseStartHostApplicationsAfterZkooIsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string CommonStrings_Preferences {
            get {
                return ResourceManager.GetString("CommonStrings_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string CommonStrings_Progress {
            get {
                return ResourceManager.GetString("CommonStrings_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Device.
        /// </summary>
        public static string CommonStrings_ResetDevice {
            get {
                return ResourceManager.GetString("CommonStrings_ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Device?.
        /// </summary>
        public static string CommonStrings_ResetDeviceConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_ResetDeviceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string CommonStrings_ResetSettings {
            get {
                return ResourceManager.GetString("CommonStrings_ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings to Default?.
        /// </summary>
        public static string CommonStrings_ResetSettingsConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_ResetSettingsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string CommonStrings_Right {
            get {
                return ResourceManager.GetString("CommonStrings_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings to Device.
        /// </summary>
        public static string CommonStrings_SaveSettingsToFlash {
            get {
                return ResourceManager.GetString("CommonStrings_SaveSettingsToFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings to Device?.
        /// </summary>
        public static string CommonStrings_SaveSettingsToFlashConfirmation {
            get {
                return ResourceManager.GetString("CommonStrings_SaveSettingsToFlashConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity and Specificity.
        /// </summary>
        public static string CommonStrings_SensitivityAndSpecificity {
            get {
                return ResourceManager.GetString("CommonStrings_SensitivityAndSpecificity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string CommonStrings_Settings {
            get {
                return ResourceManager.GetString("CommonStrings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string CommonStrings_Skip {
            get {
                return ResourceManager.GetString("CommonStrings_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string CommonStrings_Start {
            get {
                return ResourceManager.GetString("CommonStrings_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string CommonStrings_Tap {
            get {
                return ResourceManager.GetString("CommonStrings_Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string CommonStrings_Top {
            get {
                return ResourceManager.GetString("CommonStrings_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CommonStrings_Value {
            get {
                return ResourceManager.GetString("CommonStrings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string CommonStrings_Width {
            get {
                return ResourceManager.GetString("CommonStrings_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you exit {0}?.
        /// </summary>
        public static string CommonStrings_WouldYouExitApplication0 {
            get {
                return ResourceManager.GetString("CommonStrings_WouldYouExitApplication0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO recognize your hands..
        /// </summary>
        public static string CommonStrings_ZkooRecognizeYourHands {
            get {
                return ResourceManager.GetString("CommonStrings_ZkooRecognizeYourHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Chinese_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Chinese_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_English_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_English_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Japanese_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Japanese_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_Type_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use OS Culture.
        /// </summary>
        public static string CultureInfoAndDescriptionDetail_UseOSCulture_Description {
            get {
                return ResourceManager.GetString("CultureInfoAndDescriptionDetail_UseOSCulture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByHidReportUpdatedEvent_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByHidReportUpdatedEvent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 fps.
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByTimer30Fps_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByTimer30Fps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 fps.
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_ByTimer60Fps_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_ByTimer60Fps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Cursor Drawing Frequency (Smaller Value for Lower Spec PC).
        /// </summary>
        public static string CursorDrawingTimingMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("CursorDrawingTimingMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginner: For slower hand moving and easier tapping.  2 cursors cannot cross..
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard: For standard speed hand moving.  2 cursors can cross..
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fruit Ninja: Good for Fruit Ninja Game.  Cut fruits by fast moving opened hand..
        /// </summary>
        public static string CursorSpeedAndPrecisionModeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("CursorSpeedAndPrecisionModeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: Landscape.
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value0_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 90: Portrait (flipped).
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value1_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180: Landscape (flipped).
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value2_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270: Portrait.
        /// </summary>
        public static string DeviceRotationAngleInClockwiseDetail_Value3_Description {
            get {
                return ResourceManager.GetString("DeviceRotationAngleInClockwiseDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Camera.
        /// </summary>
        public static string DeviceUsageDetail_Value0_Description {
            get {
                return ResourceManager.GetString("DeviceUsageDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Camera.
        /// </summary>
        public static string DeviceUsageDetail_Value1_Description {
            get {
                return ResourceManager.GetString("DeviceUsageDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Device DevicePath.
        /// </summary>
        public static string EgsDevice_CameraDeviceDevicePath_Description {
            get {
                return ResourceManager.GetString("EgsDevice_CameraDeviceDevicePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Serial Number.
        /// </summary>
        public static string EgsDevice_DeviceSerialNumber_Description {
            get {
                return ResourceManager.GetString("EgsDevice_DeviceSerialNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Status.
        /// </summary>
        public static string EgsDevice_DeviceStatusDetailString_Description {
            get {
                return ResourceManager.GetString("EgsDevice_DeviceStatusDetailString_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        public static string EgsDevice_FirmwareVersion_Description {
            get {
                return ResourceManager.GetString("EgsDevice_FirmwareVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware Type.
        /// </summary>
        public static string EgsDevice_HardwareType_Description {
            get {
                return ResourceManager.GetString("EgsDevice_HardwareType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Device DevicePath.
        /// </summary>
        public static string EgsDevice_HidDeviceDevicePath_Description {
            get {
                return ResourceManager.GetString("EgsDevice_HidDeviceDevicePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature [C].
        /// </summary>
        public static string EgsDevice_TemperatureInCelsius_Description {
            get {
                return ResourceManager.GetString("EgsDevice_TemperatureInCelsius_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature [F].
        /// </summary>
        public static string EgsDevice_TemperatureInFahrenheit_Description {
            get {
                return ResourceManager.GetString("EgsDevice_TemperatureInFahrenheit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Longer Distance Needs More CPU Usage).
        /// </summary>
        public static string EgsDeviceFaceDetectionOnHost_LongerDistanceNeedsMoreCpuUsage {
            get {
                return ResourceManager.GetString("EgsDeviceFaceDetectionOnHost_LongerDistanceNeedsMoreCpuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Detectable Distance [m].
        /// </summary>
        public static string EgsDeviceFaceDetectionOnHost_MaxDetectableDistanceInMeter_Description {
            get {
                return ResourceManager.GetString("EgsDeviceFaceDetectionOnHost_MaxDetectableDistanceInMeter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will retry sending image file again..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_AppWillRetrySendingImageAgain {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_AppWillRetrySendingImageAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Firmware Update.
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DeviceFirmwareUpdate {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DeviceFirmwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device firmware update was canceled..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuCanceled {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device firmware update was completed..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuCompleted {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device firmware update was failed..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuFailed {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file is invalid..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DfuImageFileIsInvalid {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DfuImageFileIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not disconnect ZKOO from AC adapter and PC..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_DoNotDisconnectTheDevice {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_DoNotDisconnectTheDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please update device firmware to use ZKOO and ZKOO application by selecting OK.  During update, you need to reboot ZKOO a few times..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_PleaseUpdateDeviceFirmware {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_PleaseUpdateDeviceFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the firmware update process from the beginning..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_RestartDfuFromBeginning {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_RestartDfuFromBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Device Firmware.
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_UpdateDeviceFirmware {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_UpdateDeviceFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO needs reboot..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsReboot {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect ZKOO with AC adapter and PC and check LED is on..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsToConnectPowerCable {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsToConnectPowerCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please disconnect ZKOO from AC adapter and PC and check LED is off..
        /// </summary>
        public static string EgsDeviceFirmwareUpdateModel_ZkooNeedsToDisconnectPowerCable {
            get {
                return ResourceManager.GetString("EgsDeviceFirmwareUpdateModel_ZkooNeedsToDisconnectPowerCable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Image Resolution.
        /// </summary>
        public static string EgsDeviceSettings_CameraViewImageSourceBitmapSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CameraViewImageSourceBitmapSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View Image Source Rect in Capture Image.
        /// </summary>
        public static string EgsDeviceSettings_CameraViewImageSourceRectInCaptureImage_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CameraViewImageSourceRectInCaptureImage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binning Mode.
        /// </summary>
        public static string EgsDeviceSettings_CaptureBinning_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureBinning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Mode.
        /// </summary>
        public static string EgsDeviceSettings_CaptureExposureMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureExposureMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Frame Per Second.
        /// </summary>
        public static string EgsDeviceSettings_CaptureFps_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureFps_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Image Size.
        /// </summary>
        public static string EgsDeviceSettings_CaptureImageSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureImageSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Parameters.
        /// </summary>
        public static string EgsDeviceSettings_CaptureManualExposureParameters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CaptureManualExposureParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Usage.
        /// </summary>
        public static string EgsDeviceSettings_CursorSpeedAndPrecisionMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_CursorSpeedAndPrecisionMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Screen Orientation.
        /// </summary>
        public static string EgsDeviceSettings_DeviceRotationAngleInClockwise_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_DeviceRotationAngleInClockwise_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ZKOO for.
        /// </summary>
        public static string EgsDeviceSettings_DeviceUsage_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_DeviceUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Detection Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_FaceDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Detection Method.
        /// </summary>
        public static string EgsDeviceSettings_FaceDetectionMethod_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceDetectionMethod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Detection Scale (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_FaceDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Select a Player.
        /// </summary>
        public static string EgsDeviceSettings_FaceSelectionMethodKind_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FaceSelectionMethodKind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture by Fast Moving Hands.
        /// </summary>
        public static string EgsDeviceSettings_FastMovingHandsGestureMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_FastMovingHandsGestureMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Detection Parameters.
        /// </summary>
        public static string EgsDeviceSettings_HandDetectionParameters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_HandDetectionParameters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Machine OS.
        /// </summary>
        public static string EgsDeviceSettings_HostMachineOperatingSystem_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_HostMachineOperatingSystem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Faces.
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectFaces_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectFaces_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Faces on Device.
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectFacesOnDevice_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectFacesOnDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Hands.
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectHands_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectHands_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Hands on Device.
        /// </summary>
        public static string EgsDeviceSettings_IsToDetectHandsOnDevice_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDetectHandsOnDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw Borders on Camera View Image By Device.
        /// </summary>
        public static string EgsDeviceSettings_IsToDrawBordersOnCameraViewImageByDevice_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToDrawBordersOnCameraViewImageByDevice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Face Detection Region.
        /// </summary>
        public static string EgsDeviceSettings_IsToFixFaceDetectionRegion_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixFaceDetectionRegion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Hand Detection Regions.
        /// </summary>
        public static string EgsDeviceSettings_IsToFixHandDetectionRegions_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixHandDetectionRegions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Hand Tracking Areas.
        /// </summary>
        public static string EgsDeviceSettings_IsToFixHandTrackingAreas_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixHandTrackingAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Screen Mapped Areas.
        /// </summary>
        public static string EgsDeviceSettings_IsToFixScreenMappedAreas_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToFixScreenMappedAreas_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure Temperature.
        /// </summary>
        public static string EgsDeviceSettings_IsToMonitorTemperature_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToMonitorTemperature_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Touch Information to Apps.
        /// </summary>
        public static string EgsDeviceSettings_IsToSendEgsGestureHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendEgsGestureHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Hovering State on Touch Information to OS (On Windows 10, problems can happen).
        /// </summary>
        public static string EgsDeviceSettings_IsToSendHoveringStateOnTouchScreenHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendHoveringStateOnTouchScreenHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Touch Information to OS.
        /// </summary>
        public static string EgsDeviceSettings_IsToSendTouchScreenHidReport_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_IsToSendTouchScreenHidReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Close Hand.
        /// </summary>
        public static string EgsDeviceSettings_LeftHandCloseHand_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandCloseHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Detection Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_LeftHandDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Detection Scale (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_LeftHandDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Inner Rotation.
        /// </summary>
        public static string EgsDeviceSettings_LeftHandInnerRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandInnerRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Outer Rotation.
        /// </summary>
        public static string EgsDeviceSettings_LeftHandOuterRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandOuterRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Screen Mapped Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_LeftHandScreenMappedAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandScreenMappedAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand Tracking Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_LeftHandTrackingAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LeftHandTrackingAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal Length [mm].
        /// </summary>
        public static string EgsDeviceSettings_LensEquivalentFocalLengthInMillimeters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LensEquivalentFocalLengthInMillimeters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F Number.
        /// </summary>
        public static string EgsDeviceSettings_LensFNumber_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_LensFNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Set ID.
        /// </summary>
        public static string EgsDeviceSettings_ModelSetId_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_ModelSetId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Mode.
        /// </summary>
        public static string EgsDeviceSettings_PowerMode_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_PowerMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Close Hand.
        /// </summary>
        public static string EgsDeviceSettings_RightHandCloseHand_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandCloseHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Detection Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_RightHandDetectionAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandDetectionAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Detection Scale (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_RightHandDetectionScaleOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandDetectionScaleOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Inner Rotation.
        /// </summary>
        public static string EgsDeviceSettings_RightHandInnerRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandInnerRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Outer Rotation.
        /// </summary>
        public static string EgsDeviceSettings_RightHandOuterRotation_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandOuterRotation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Screen Mapped Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_RightHandScreenMappedAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandScreenMappedAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand Tracking Area (when fixed).
        /// </summary>
        public static string EgsDeviceSettings_RightHandTrackingAreaOnFixed_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_RightHandTrackingAreaOnFixed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Mapped Area Resolution Size on Device.
        /// </summary>
        public static string EgsDeviceSettings_ScreenMappedAreaResolutionSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_ScreenMappedAreaResolutionSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure [ms].
        /// </summary>
        public static string EgsDeviceSettings_SensorExposureTimeInMilliseconds_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_SensorExposureTimeInMilliseconds_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Pixel Side Length [mm].
        /// </summary>
        public static string EgsDeviceSettings_SensorOnePixelSideLengthInMillimeters_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_SensorOnePixelSideLengthInMillimeters_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness of Status LED.
        /// </summary>
        public static string EgsDeviceSettings_StatusLedBrightnessMaximum_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_StatusLedBrightnessMaximum_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Interface Kind.
        /// </summary>
        public static string EgsDeviceSettings_TouchInterfaceKind_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TouchInterfaceKind_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Target Screen Size.
        /// </summary>
        public static string EgsDeviceSettings_TouchTargetScreenSize_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TouchTargetScreenSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Number of Trackable Objects.
        /// </summary>
        public static string EgsDeviceSettings_TrackableHandsCount_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_TrackableHandsCount_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Communication Protocol Revision.
        /// </summary>
        public static string EgsDeviceSettings_UsbProtocolRevision_Description {
            get {
                return ResourceManager.GetString("EgsDeviceSettings_UsbProtocolRevision_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO Device.
        /// </summary>
        public static string FaceDetectionMethodDetail_Value0_Description {
            get {
                return ResourceManager.GetString("FaceDetectionMethodDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Application (Higher Accuracy).
        /// </summary>
        public static string FaceDetectionMethodDetail_Value1_Description {
            get {
                return ResourceManager.GetString("FaceDetectionMethodDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Solution by SDK Users.
        /// </summary>
        public static string FaceDetectionMethodDetail_Value2_Description {
            get {
                return ResourceManager.GetString("FaceDetectionMethodDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto: Select a person who moves a hand automatically.
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value0_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One by One: Select a person one by one to find who moves a hand.
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value1_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Center: Select the most center person in Camera View.
        /// </summary>
        public static string FaceSelectionMethodKindDetail_Value2_Description {
            get {
                return ResourceManager.GetString("FaceSelectionMethodKindDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FastMovingHandsGestureModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("FastMovingHandsGestureModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        public static string FastMovingHandsGestureModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("FastMovingHandsGestureModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Information.
        /// </summary>
        public static string HardwareTypeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO for Kickstarter Backers.
        /// </summary>
        public static string HardwareTypeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA2150 + IMX208.
        /// </summary>
        public static string HardwareTypeDetail_Value2_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MA2150 + IMX208 + PIC.
        /// </summary>
        public static string HardwareTypeDetail_Value3_Description {
            get {
                return ResourceManager.GetString("HardwareTypeDetail_Value3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string HostMachineOperatingSystemDetail_Value0_Description {
            get {
                return ResourceManager.GetString("HostMachineOperatingSystemDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string HostMachineOperatingSystemDetail_Value1_Description {
            get {
                return ResourceManager.GetString("HostMachineOperatingSystemDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Fingers for TV.
        /// </summary>
        public static string ModelSetIdDetail_Value0_Description {
            get {
                return ResourceManager.GetString("ModelSetIdDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wands?.
        /// </summary>
        public static string ModelSetIdDetail_Value1_Description {
            get {
                return ResourceManager.GetString("ModelSetIdDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Found Hand.
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_FirstFoundHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_FirstFoundHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Hand.
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_LeftHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_LeftHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_None_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_None_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Hand.
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_RightHand_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_RightHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Mouse Cursor&apos;s Position to Follow Gesture Cursor&apos;s Position.
        /// </summary>
        public static string MouseCursorPositionUpdatedByGestureCursorMethodDetail_Type_Description {
            get {
                return ResourceManager.GetString("MouseCursorPositionUpdatedByGestureCursorMethodDetail_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesture Cursor Type.
        /// </summary>
        public static string OnePersonBothHandsViewModel_GestureCursorType_Description {
            get {
                return ResourceManager.GetString("OnePersonBothHandsViewModel_GestureCursorType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gesture Cursors.
        /// </summary>
        public static string OnePersonBothHandsViewModel_IsToShowGestureCursors_Description {
            get {
                return ResourceManager.GetString("OnePersonBothHandsViewModel_IsToShowGestureCursors_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string PowerModeDetail_Value0_Description {
            get {
                return ResourceManager.GetString("PowerModeDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StandingBy.
        /// </summary>
        public static string PowerModeDetail_Value1_Description {
            get {
                return ResourceManager.GetString("PowerModeDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string SettingsUserControl_AdvancedSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_AdvancedSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog Gain (1-32): .
        /// </summary>
        public static string SettingsUserControl_AnalogGain_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_AnalogGain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string SettingsUserControl_BasicSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_BasicSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera View.
        /// </summary>
        public static string SettingsUserControl_CameraViewSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_CameraViewSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        public static string SettingsUserControl_DeveloperSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_DeveloperSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exvision.
        /// </summary>
        public static string SettingsUserControl_ExvisionSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_ExvisionSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options for Lower Spec PC.
        /// </summary>
        public static string SettingsUserControl_OptionsForLowerSpecPc_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_OptionsForLowerSpecPc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tutorial.
        /// </summary>
        public static string SettingsUserControl_StartTutorial_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_StartTutorial_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial App.
        /// </summary>
        public static string SettingsUserControl_TutorialAppSettings_Description {
            get {
                return ResourceManager.GetString("SettingsUserControl_TutorialAppSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiTouch.
        /// </summary>
        public static string TouchInterfaceKindDetail_Value0_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value0_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleTouch (for Android).
        /// </summary>
        public static string TouchInterfaceKindDetail_Value1_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value1_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string TouchInterfaceKindDetail_Value2_Description {
            get {
                return ResourceManager.GetString("TouchInterfaceKindDetail_Value2_Description", resourceCulture);
            }
        }
    }
}
