//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egs.ZkooTutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NarrationTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NarrationTexts() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egs.ZkooTutorial.Properties.NarrationTexts", typeof(NarrationTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Let&apos;s practice displaying the Gesture Cursor on the screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sit in front of the ZKOO and ensure both your face &amp; upper body are positioned in the center of the Camera View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO has detected your face. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00300_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the &quot;Video&quot; button by using a mouse or gesture to replay the Tutorial Video. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the &quot;Practice&quot; button by using a mouse or gesture to retry this practice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click on the &quot;Next&quot; button by using a mouse or gesture to skip this practice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00600_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO has detected your hand and is now tracking it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message00900_TextKey {
            get {
                return ResourceManager.GetString("View001_Message00900_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After ZKOO detects your hand, the shape of the Gesture Tracking Area changes.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01000_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01000_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A Pointer is shown at the center of your palm.  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01100_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should now see the Gesture Cursor on the screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01200_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To stop displaying the cursor, slide your hand out of the Gesture Tracking Area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01300_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO has stopped tracking your hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01400_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s practice letting ZKOO detect your hand to bring up the Gesture Cursor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01500_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try showing and hiding the Cursor 5 times.  You have 1 minute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View001_Message01600_TextKey {
            get {
                return ResourceManager.GetString("View001_Message01600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let’s practice moving the Gesture Cursor. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When you move your hand, the Gesture Cursor moves along with it. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circles 1, 2, 3, and 4 in this order. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circle number 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00501_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00501_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circle number 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00502_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00502_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circle number 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00503_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00503_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circle number 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00504_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00504_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Once you get the hang of it, you should be able to easily control the Gesture Cursor without relying on the Camera View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View002_Message00700_TextKey {
            get {
                return ResourceManager.GetString("View002_Message00700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let’s practice the tap gesture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Gesture Cursor to circle number 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   While keeping your thumb sticking out to the side, curl your 4 fingers toward your palm then quickly uncurl. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00300_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s practice tapping. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A voice will count to 3.  Within that time, you will need to curl and quickly uncurl your fingers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s begin.  1, 2, 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00700_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Again.  1, 2, 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00800_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00800_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When you leave your fingers curled for a while, ZKOO detects it as a long press. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message00900_TextKey {
            get {
                return ResourceManager.GetString("View003_Message00900_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In order to tap, make sure you immediately uncurl your 4 fingers after the initial curl. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01000_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01000_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please tap on circles 1, 2, 3 &amp; 4 in that order.  Repeat 3 times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01100_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Cursor to circle number 1 and tap it 3 times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01201_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01201_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap circle number 2 three times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01202_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01202_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap circle number 3 three times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01203_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01203_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tap circle number 4 three times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View003_Message01204_TextKey {
            get {
                return ResourceManager.GetString("View003_Message01204_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let’s practice the drag gesture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Gesture Cursor to the small circle in the upper-right corner of the screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remember to keep your thumb sticking out while curling your other fingers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   While keeping your fingers curled, move your hand to drag the small circle inside of the bigger circle on the bottom right of the screen. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no need to make large movements with your hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00600_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   After moving the circle to the target area, please open your fingers. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00700_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have now successfully dragged an object. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00800_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00800_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab the small circle inside area 1 and drag it to areas 2, 3, 4 in that order. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message00900_TextKey {
            get {
                return ResourceManager.GetString("View004_Message00900_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grab the small circle inside area 1 and drag it to area 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message01000_TextKey {
            get {
                return ResourceManager.GetString("View004_Message01000_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Gesture Cursor on top of the small circle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message01100_TextKey {
            get {
                return ResourceManager.GetString("View004_Message01100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Curl your 4 fingers to grab the small circle. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message01200_TextKey {
            get {
                return ResourceManager.GetString("View004_Message01200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When dragging, keep your fingers curled with your thumb sticking out to the side. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message01600_TextKey {
            get {
                return ResourceManager.GetString("View004_Message01600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop them in order. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message01700_TextKey {
            get {
                return ResourceManager.GetString("View004_Message01700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep your fingers curled and drag it to area 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02102_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02102_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep your fingers curled and drag it to area 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02103_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02103_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep your fingers curled and drag it to area 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02104_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02104_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue to move it to area 2. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02202_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02202_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue to move it to area 3. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02203_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02203_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Continue to move it to area 4. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View004_Message02204_TextKey {
            get {
                return ResourceManager.GetString("View004_Message02204_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let’s practice the flick gesture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s scroll through the items inside the rectangular outlines, using the flick gesture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move the Gesture Cursor to the center of the window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00300_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep your thumb sticking out and curl your 4 fingers slightly, just like the drag gesture. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To flick, start moving your hand slightly in one direction and open it quickly. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no need to make large movements with your hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00600_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Just keep moving your hand and open it quickly to flick. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00700_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The timing for opening your hand is a bit different from dragging. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00800_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00800_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Curl your fingers and while moving your hand in one direction, quickly open your hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message00900_TextKey {
            get {
                return ResourceManager.GetString("View005_Message00900_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can achieve a smooth flick by springing open your hands. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message01000_TextKey {
            get {
                return ResourceManager.GetString("View005_Message01000_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You have now learned all of the basic gestures. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View005_Message02700_TextKey {
            get {
                return ResourceManager.GetString("View005_Message02700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please face ZKOO and let it detect your face. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO cannot detect your face.  Make sure your face &amp; upper body are positioned in the center of the Camera View. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00200_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00200_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not see the Camera View, refer to the Setup Guide on how to set up your ZKOO. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00300_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move your hand inside the Gesture Tracking Area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00400_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00400_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You will see 2 rectangular outlines appear next to your face.  This represents the Gesture Tracking Areas. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move your hand inside the Gesture Tracking Area.  Make sure your arms are in a comfortable, relaxed position. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00600_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00600_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open your hand and spread your fingers.  Slightly wave your hand. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00700_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00700_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now, move your hand out of the Gesture Tracking Area to end the gesture control. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View100_Message00800_TextKey {
            get {
                return ResourceManager.GetString("View100_Message00800_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s practice. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00000_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00000_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00100_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00100_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One more time. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00201_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00201_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Two more times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00202_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00202_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Three more times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00203_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00203_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Four more times. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00204_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00204_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s try this 5 more times.  You have 1 minute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00215_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00215_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s try this 5 more times.  You have 2 minute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00225_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00225_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time&apos;s up.  Please try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00300_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00300_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well done.  Let&apos;s practice something else. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00500_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00500_TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Go ahead. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string View101_Message00600_TextKey {
            get {
                return ResourceManager.GetString("View101_Message00600_TextKey", resourceCulture);
            }
        }
    }
}
