//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egs.ZkooTutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egs.ZkooTutorial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By selecting NEXT, you agree to Exvision&apos;s.
        /// </summary>
        public static string ZkooTutorialModel_BySelectingNext_YouAgreeToExvisions {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_BySelectingNext_YouAgreeToExvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete..
        /// </summary>
        public static string ZkooTutorialModel_Complete {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User License Agreement.
        /// </summary>
        public static string ZkooTutorialModel_EndUserLicenseAgreement {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_EndUserLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to play a video..
        /// </summary>
        public static string ZkooTutorialModel_FailedToPlayAVideo {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_FailedToPlayAVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the EULA..
        /// </summary>
        public static string ZkooTutorialModel_IAcceptTheEula {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_IAcceptTheEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s start tutorials!.
        /// </summary>
        public static string ZkooTutorialModel_LetsStartTutorials {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_LetsStartTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ZkooTutorialModel_Next {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tap circles in order..
        /// </summary>
        public static string ZkooTutorialModel_PleaseTapCirclesInOrder {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_PleaseTapCirclesInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string ZkooTutorialModel_PrivacyPolicy {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string ZkooTutorialModel_Replay {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string ZkooTutorialModel_Retry {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings menu can be opened by tapping on Camera View or right-clicking icon on the notification area..
        /// </summary>
        public static string ZkooTutorialModel_SettingsMenuCanBeOpenedBy {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_SettingsMenuCanBeOpenedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip video?.
        /// </summary>
        public static string ZkooTutorialModel_SkipVideo {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_SkipVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Tutorial again when this application is launched..
        /// </summary>
        public static string ZkooTutorialModel_StartTutorialAgainWhenThisApplicationIsLaunched {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_StartTutorialAgainWhenThisApplicationIsLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        public static string ZkooTutorialModel_TryAgain {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO will be in the center of the screen.
        ///Sit away 7ft.
        ///Toward the front of the camera, in the middle.
        ///To adjust the angle of the camera to see the Setup Guide..
        /// </summary>
        public static string ZkooTutorialModel_TryAgainDetail {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TryAgainDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial completes!.
        /// </summary>
        public static string ZkooTutorialModel_TutorialCompletes {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TutorialCompletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO Tutorial.
        /// </summary>
        public static string ZkooTutorialModel_TutorialWindowTitle {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TutorialWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string ZkooTutorialModel_Video {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done..
        /// </summary>
        public static string ZkooTutorialModel_WellDone {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_WellDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can start this Tutorial again from Settings &gt; Basic..
        /// </summary>
        public static string ZkooTutorialModel_YouCanStartTutorialFromSettingsBasic {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_YouCanStartTutorialFromSettingsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO tutorial is starting..
        /// </summary>
        public static string ZkooTutorialModel_ZkooTutorialIsStarting {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_ZkooTutorialIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZKOO tutorial needs internet connection..
        /// </summary>
        public static string ZkooTutorialModel_ZkooTutorialNeedsInternetConnections {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_ZkooTutorialNeedsInternetConnections", resourceCulture);
            }
        }
    }
}
