//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Egs.ZkooTutorial.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Egs.ZkooTutorial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   By selecting NEXT, you agree to Exvision&apos;s に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_BySelectingNext_YouAgreeToExvisions {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_BySelectingNext_YouAgreeToExvisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_Complete {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End User License Agreement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_EndUserLicenseAgreement {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_EndUserLicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to play a video. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_FailedToPlayAVideo {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_FailedToPlayAVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I accept the EULA. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_IAcceptTheEula {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_IAcceptTheEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s start tutorials! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_LetsStartTutorials {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_LetsStartTutorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_Next {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please tap circles in order. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_PleaseTapCirclesInOrder {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_PleaseTapCirclesInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Privacy Policy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_PrivacyPolicy {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replay に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_Replay {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Retry に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_Retry {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings menu can be opened by tapping on Camera View or right-clicking ZKOO icon on the notification area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_SettingsMenuCanBeOpenedBy {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_SettingsMenuCanBeOpenedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip video? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_SkipVideo {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_SkipVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Tutorial again when ZKOO application is launched. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_StartTutorialAgainWhenZkooApplicationIsLaunched {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_StartTutorialAgainWhenZkooApplicationIsLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_TryAgain {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO will be in the center of the screen.
        ///Sit away 7ft.
        ///Toward the front of the camera, in the middle.
        ///To adjust the angle of the camera to see the Setup Guide. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_TryAgainDetail {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TryAgainDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tutorial completes! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_TutorialCompletes {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TutorialCompletes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO Tutorial に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_TutorialWindowTitle {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_TutorialWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Video に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_Video {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Well done. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_WellDone {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_WellDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can start this Tutorial again from Settings &gt; Basic. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_YouCanStartTutorialFromSettingsBasic {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_YouCanStartTutorialFromSettingsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO tutorial is starting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_ZkooTutorialIsStarting {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_ZkooTutorialIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZKOO tutorial needs internet connection. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ZkooTutorialModel_ZkooTutorialNeedsInternetConnections {
            get {
                return ResourceManager.GetString("ZkooTutorialModel_ZkooTutorialNeedsInternetConnections", resourceCulture);
            }
        }
    }
}
